# Generated by Django 5.1.3 on 2024-12-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="title",
            new_name="tasks",
        ),
    ]
