# Generated by Django 5.1.3 on 2024-12-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_rename_title_task_tasks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="tasks",
            new_name="task",
        ),
    ]
