# Generated by Django 5.1.3 on 2024-12-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_rename_tasks_task_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_checked",
            field=models.BooleanField(default=False),
        ),
    ]
