# Generated by Django 5.1.3 on 2024-12-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_task_is_checked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_checked",
        ),
    ]
