# Generated by Django 5.1.3 on 2024-12-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_remove_task_is_checked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
